/**Cedula maker
 * Generated by;
 * Joaquim Breno
 */


#include <stdio.h>
#include <locale.h>

int main(void){
    int cash, d, r;
    printf("Olá! Meu nome é Kodi, seu matemático digital. Siga meus passos e seu resultado será um sucesso.\n");
    printf("Digite a quantidade de dinheiro que deseja em cédulas:\n");
    scanf("%d", &cash);
    d = cash/100;
    r = cash%100;
    if( d != 0){
        printf("\033[0;31m O número de cédulas de 100 é %d\n", d);
    }
    cash = r;
    d = cash/50;
    r = cash%50;
    if( d != 0){
        printf("\033[0;32m O número de cédulas de 50 é %d\n", d);
    }    
    cash = r;
    d = cash/20;
    r = cash%20;
    if( d != 0){
        printf("\033[0;33m O número de cédulas de 20 é %d\n", d);
    }        
    cash = r;
    d = cash/10;
    r = cash%10;
    if( d != 0){
        printf("\033[0;34m O número de cédulas de 10 é %d\n", d);
    }    
    cash = r;
    d = cash/5;
    r = cash%5;
    if( d != 0){
        printf("\033[0;35m O número de cédulas de 5 é %d\n", d);
    }    
   cash = r;
    d = cash/1;
    r = cash%1;
    if( d != 0){
        printf("\033[0;36m O número de cédulas de 1 (in memoriam, :D kkk) é %d\n", d);
    }    


return(0);
}