/**Aritmetic Schedule
 * Generated by;
 * Joaquim Breno
 */
#include <stdio.h>
#include <locale.h>

int main(void){
    setlocale(LC_ALL, "portuguese-brazilian");
    float x1, x2, x3, s, r1;
    printf("Olá, meu nome é Kodi! Calcule a soma e amédia aritmética de 3 valores, siga meus passos e seu resultado será um sucesso\n\n");
    printf("Digite o primeiro valor:\n");
    scanf("%f", &x1);
    printf("Digite o segundo valor:\n");
    scanf("%f", &x2); 
    printf("Digite o terceiro valor:\n");
    scanf("%f", &x3);    

    s = x1 + x2 + x3;

    printf("O valor da soma é %.2f\n", s);

    r1 = s/3;

    printf("O valor da média aritmética é %.2f\n", r1);

    
    return(0);
}