/**RightWeight
 * Calculadora de peso ideal para homens e mulheres
 * Generated by;
 * Joaquim Breno
 */

#include <stdio.h>
#include <locale.h>

int main(void){
    float h, w;
    char sex;
    printf(" Olá! Sou o Kodi, seu matemático digital, siga meus passos e seu resultado será um sucesso!\n\n");


    printf(" Necessito saber seu sexo. Por favor, digite F para feminino ou M para masculino \n");
    scanf("%c", &sex);
    if( sex == 'F'){
        printf(" Você é do sexo feminino! Certo, necessito da sua altura, digite em metros por favor:\n");
        scanf("%f", &h);
        w = (62.1*h) - 44.7;
        printf(" Seu peso ideal é %.2f kg, espero que não fique triste com o resultado\n", w);
    }
    if( sex == 'M'){
        printf(" Você é do sexo masculino! Certo, necessito da sua altura, digite em metros por favor:\n");
        scanf("%f", &h);
        w = (72.7*h) - 58;
        printf(" Seu peso ideal é %.2f kg, espero que não fique triste com o resultado\n", w);
    }
    else{
        return(0);
    }    
    return(0);
}