
// Function Menu With Activities
// Generated by;
// Joaquim Breno
// “Programs must be written for people to read, and only incidentally for machines to execute.”
//― Harold Abelson


#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#include <time.h>


void Starting();
void Default();
void Potention();
void Progressions();
void PrimeNumber();
void PAIdentifier();
void Fibonacci();

int main(){
    int opcao;
    print:
    Starting();
    setlocale(LC_ALL, "portuguese-brazilian");
    printf("DIGITE UMA ALTERNATIVA PARA ACESSAR:\n");
    printf("1) Questão 1\n");
    printf("2) Questão 2\n");
    printf("3) Questão 3\n");
    printf("4) Questão 4\n");
    printf("5) Questão 5\n");
    printf("0) Sair\n");
    scanf("%d", &opcao);
    system("clear");
    switch (opcao){
    case 0:
        printf("Até a próxima!\n");
        return(0);
    case 1:
        Potention();
        break;
    case 2:
        Progressions();
        break;
    case 3:
        PrimeNumber();
        break; 
    case 4:
        PAIdentifier();
        break;
    case 5:
        Fibonacci();
        break;
    default: 
        Default();
        system("clear");
        goto print;
    }
}

void Starting()
{
    printf("----------------------------------------------\n");
    printf("---------------Banco de Questões--------------\n");
    printf("----------------------------------------------\n");
}

void Default(){
   printf("Digitaste um caractere errado.\n"); 
   sleep(2);
   return;
}

void Potention(){
    int base, expoente, potencia, resultado;
    printf("Irei calcular sua potencialização, digite a base e o expoente\n");
    printf("Digite a base:\n");
    scanf("%d", &base);
    printf("Digite o expoente:\n");
    scanf("%d", &expoente);   

    resultado = 1; 
        for(potencia = 1; potencia <= expoente; potencia++){
                resultado = resultado * base;
        } 

    printf("O resultado é %d\n", resultado);
}

void Progressions(){
    float razao, t1, tn, soma, resultado;
    int n, i;
    char prog;
    prog == 'prog';

    inicio:
    while(prog != 'p' && prog != 'g'){
        puts("Qual progressão deseja efetuar?");
        puts("(p) Para Progressão Aritmética");
        puts("(g) Para Progressão Geométrica");
        scanf("%c", &prog);
        if(prog != 'p' && prog != 'g'){
        printf("Caractere Inválido");}
        system("clear");
    }
    
    printf("Digite o primeiro termo :");
    scanf("%f", &t1);
    printf("Digite a razão :");
    scanf("%f", &razao);
    printf("Digite o número de termos :");
    scanf("%d", &n); 

        if(t1 >= 0 && razao >= 0 && n>= 0){

            soma = 0;

            if(prog == 'p'){
                for( i = 1; i<=n; i++){
                    tn = t1 + (i-1)*razao;
                    printf("Número %d = %.2f\n", i, tn);
                    soma = soma + tn;
                }
                
                printf("A soma entre os termos é %.2f\n", soma);
            }

            if(prog == 'g'){
                resultado = 1; 
                for( i = 1; i<=n; i++){
                    resultado = resultado * razao; /** potencialização da razão*/
                    tn = t1 * resultado; /** Mesma coisa que an = a1*q(n-1), mas com um toque de charme */
                    printf("Número %d = %.2f\n", i, tn);
                    soma = soma + tn;
                }

                printf("A soma entre os termos é %.2f\n", soma);
            }
        }
        else{
            printf("Não calculo números negativos, me poupe.\n");
            sleep(2);
            system("clear");
            goto inicio;
        }
}

void PrimeNumber(){
    float resto;
    int n, primo, zero;

    print:
    printf("Digite um número maior que zero e direi se é primo ou não:");
    scanf("%d", &primo);
    zero = 0;

        if(primo>0){     
            for( n = 1; n <= primo; n++){
                resto = primo %n; 
                if (resto == 0) {
                    zero = zero + 1;
                }
            }
                if(zero>2 || zero <2){
                    puts("Uma pena, seu número não é primo");
                }
                if(zero == 2){
                    puts("Seu número é primo");
                }
        }
        else{
            goto print;
        }
}

void PAIdentifier(){
    int a, b, nRazao, nRazaoAtual, boolean, contador;
    char c;
    c == 'c';

    print:
    printf("\nDigite o 1º número:");
    scanf("%d", &a);
    printf("\nDigite o 2º número:");
    scanf("%d", &b);
    nRazao = b-a;
    boolean = 1;
    contador = 2;

        do{
            contador++;
            a = b ;
            printf("\nDigite o  %dº número:", contador);
            scanf("%d", &b);
            nRazaoAtual = b-a;
            if(b !=-1 && nRazaoAtual != nRazao){
                boolean = 0;
            }
        }while(b!=-1);


        if(boolean == 0){
            printf("\nA sequência não é uma PA\n"); 
        }
        else{
            printf("\nA sequência é uma PA e a razão é %d\n", nRazao);   
        }

            puts("Deseja continuar testando sequências?(S/N)");
            scanf(" %c", &c);
            if(c != 'S'){
                return;
            }
            else{
                goto print;
            }         
}

void Fibonacci(){
    int n, soma, a, b ,c;
        do{
        printf("\nQuantos termos você quer representar pela sequência de Fibonacci (Mais de 2 termos)\n");
        scanf("%d", &n);
        n=n-2;
            if(n==1){
                printf("1 1 2");
            }
            if(n>1){
                printf("1 1 2 ");
                a=1;
                b=2;
                for (soma = 1; soma < n; soma++){
                    c = b;
                    b= b + a;
                    a = c;
                    printf("%d ",b);
                }
            }
            printf("\nSe não quiser continuar digite um número menor que 2\n");
        }while(n>2);


}