
// Function Menu With Activities
// Generated by;
// Joaquim Breno
// “Programs must be written for people to read, and only incidentally for machines to execute.”
//― Harold Abelson


#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#include <time.h>

#define BLUE "\033[38;5;33m"  /*Cores*/
#define YELLOW "\033[38;5;226m"
#define RED "\033[38;5;160m"
#define GREEN "\033[38;5;190m"
#define RESET   "\x1b[0m"

void Starting(); /*Mensagem de entrada*/
void Password();
void OneToTen();
void OneToTenA();
void OneToTenB();
void OneToTenC();
void TenToTen();
void TenToTenA();
void TenToTenB();
void TenToTenC();
void TwoHundredThings();
void AandBPlan();
void AandBPlan2();
void HunchPlan();
void HunchPlan2();

int main()
{
    int opcao;
    setlocale(LC_ALL, "portuguese-brazilian");
        print:
        Starting();
        printf(" DIGITE QUAL ALTERNATIVA VOCÊ DESEJA ACESSAR:\n");
        printf(" 1 - Questão 1 \n");
        printf(" 2 - Questão 2 \n");
        printf(" 3 - Questão 3 \n");     
        printf(" 4 - Questão 4 \n");  
        printf(" 5 - Questão 5 \n"); 
        printf(" 6 - Questão 6 \n");  
        printf(" 7 - Questão 7 \n");   
        printf(" 8 - Questão 8 \n");                     
        printf(" 0 - Sair \n");
        scanf(" %d", &opcao);
        system("clear");
        switch(opcao){
            case 0:
                printf(GREEN"Até a próxima\n"RESET);
                return(0);
            case 1:
                Password();  
                goto print;
            case 2:
                OneToTen();  
                break;
            case 3:
                TenToTen();  
                break;          
            case 4:
                TwoHundredThings();
                break;
            case 5:
                AandBPlan();
                break; 
            case 6:
                AandBPlan2();
                break; 
            case 7:
                HunchPlan();
                break; 
            case 8:
                HunchPlan2();
                break;                                       
            // default:
            //     printf(RED"Digite um número válido\n"RESET);
            //     system("clear");
            //     goto print;
        }
}


void Starting()
{
    printf(YELLOW"----------------------------------------------\n");
    printf("---------------Banco de Questões--------------\n");
    printf("----------------------------------------------\n"RESET);
}

void Password(){
    int password;
    printf(YELLOW"Digite sua senha:\n"RESET);
    scanf("%d", &password);
    password = -1;
    while(password != 2020){
        printf(RED"*********Senha Inválida*********\n"RESET);
        printf(YELLOW"Digite sua senha:\n"RESET);
        scanf("%d", &password);
        system("clear");
    }
    printf(GREEN"*********Acesso Permitido*********\n"RESET);
}

void OneToTen(){
        int opcao2;
        print2:
        Starting();
        printf(" DIGITE QUAL ALTERNATIVA VOCÊ DESEJA ACESSAR:\n");
        printf(" 1) Letra A \n");
        printf(" 2) Letra B \n");
        printf(" 3) Letra C \n");
        printf(" 0) Sair \n");
        scanf(" %d", &opcao2);
        system("clear");
        switch(opcao2){
            case 0:
                printf(GREEN"Até a próxima\n"RESET);
                break;
            case 1:
                OneToTenA();  
                break; 
            case 2:
                OneToTenB();  
                break; 
            case 3:
                OneToTenC();  
                break;             
            default:
                printf(RED"Digite um número válido\n"RESET);
                system("clear");
                goto print2;
        }
}

void OneToTenA(){
    int a, b;
    printf(YELLOW"Eu conto de um a dez\n"RESET);
    a = 1;
    b = a;
    while(b<=10){  
        printf(GREEN"Número %d\n", b, RESET);    
        b = b + 1;
    }
}

void OneToTenB(){
    int a, b;
    printf(YELLOW"Eu conto de um a dez\n"RESET);
    a=1;
    b=a;
    do{   
        printf(GREEN"Número %d\n", b, RESET); 
        b= b+1;
    }while(b<=10);
}
 
void OneToTenC(){
    int a;
    printf(YELLOW"Eu conto de um a dez\n"RESET); 
    for( a=1; a<=10; a++){
        printf(GREEN"Número %d\n", a, RESET);
    }
}

void TenToTen(){
        int opcao2;
        print2:
        Starting();
        printf(" DIGITE QUAL ALTERNATIVA VOCÊ DESEJA ACESSAR:\n");
        printf(" 1) Letra A \n");
        printf(" 2) Letra B \n");
        printf(" 3) Letra C \n");
        printf(" 0) Sair \n");
        scanf(" %d", &opcao2);
        system("clear");
        switch(opcao2){
            case 0:
                printf(GREEN"Até a próxima\n"RESET);
                break;
            case 1:
                TenToTenA();  
                break; 
            case 2:
                TenToTenB();  
                break; 
            case 3:
                TenToTenC();  
                break;             
            default:
                printf(RED"Digite um número válido\n"RESET);
                system("clear");
                goto print2;
        }
}

void TenToTenA(){
    int a, b;
    printf(YELLOW"Eu conto de menos dez a dez\n"RESET);
    a = -10;
    b = a;
    while(b<=10){  
        printf(GREEN"Número %d\n", b, RESET);    
        b = b + 1;
    }
}

void TenToTenB(){
    int a, b;
    printf(YELLOW"Eu conto de menos dez a dez\n"RESET);
    a=-10;
    b=a;
    do{   
        printf(GREEN"Número %d\n", b, RESET); 
        b= b+1;
    }while(b<=10);
}
 
void TenToTenC(){
    int a;
    printf(YELLOW"Eu conto de menos dez a dez\n"RESET); 
    for( a=-10; a<=10; a++){
        printf(GREEN"Número %d\n", a, RESET);
    }
}

void TwoHundredThings(){
    int contador, par;
    printf(GREEN " Acredite em mim:\n" RESET);
    for(contador=1; contador<=200; contador++){
        if(contador % 2 == 0){
            printf(BLUE"Só aprende a programar quem escreve programas\n"RESET);
        }
        if(contador %2 !=0){
            printf(BLUE"Quem não escreve programas não aprende a programar\n"RESET);
        }
    }
}

void AandBPlan(){
    int a, b;
    input:
    printf(YELLOW" Vou contar números entre 'a' e 'b' que você digitar, sendo o 'a' sempre menor que 'b'. \n"RESET);
    printf(" Digite o número 'a': \n");   
    scanf("%d", &a);
    printf(GREEN" ----O número 'a' é: %d----\n", a);   
    printf(RESET" Digite o número 'b': \n");    
    scanf("%d", &b);
    printf(GREEN" ----O número 'b' é: %d----\n\n", b); 
    if(a>=b){
    printf(RED"\n*****Você digitou um número 'a' menor que 'b' ou igual a 'b'*****\n\n"RESET);
    goto input;
    }
    for(a = a;a<=b ; a++){
    printf(YELLOW"Número %d\n", a);
    }
    printf(GREEN"Até a próxima\n"RESET);
}

void AandBPlan2(){
    int a, b, c, progarit;/*progarit significa progressão aritmética*/
    a=-1;
    b=-1;
    while((a>b) || ((a < 0 || b < 0) || a == b )){
    printf(YELLOW" Vou contar números entre 'a' e 'b' que você digitar\n"RESET);
    printf(" Digite o número 'a': \n");   
    scanf("%d", &a);
    printf(GREEN" ----O número 'a' é: %d----\n"RESET, a);   
    printf(" Digite o número 'b': \n");    
    scanf("%d", &b);
    printf(GREEN" ----O número 'b' é: %d----\n"RESET, b); 
    if(a > b){
    printf(RED"\n*****Você digitou um número 'a' menor que 'b' ou igual a 'b'*****\n\n");
    printf("\n*****Irei trocar 'a' por 'b'*****\n\n"RESET);
    c = a;
    a = b;
    b = c;
    }
    if( a<0 || b<0 || a == b){
    printf(RED"\n*****Você digitou números negativos ou iguais*****\n\n"RESET); 
    }
    }
    for(c = 1 ; c<= b; c++){
        if(c == b){
            progarit = (c*(a+b))/2;
            printf(GREEN"A soma de todos os valores de a até b é %d\n"RESET, progarit);
        }
    }/*AQUI FAÇO O CALCULO DA PROGRESSÃO ARITMETICA, Note que 'c' tornou-se quantidade de números
    entre 'a' e 'b'*/
    printf(YELLOW"Sequência de Números:\n"RESET);
    for(a = a ;a<=b ; a++ ){
    printf(GREEN"Número %d\n"RESET, a);
    }

    printf(GREEN"Até a próxima\n"RESET);
}

void HunchPlan(){
    int palpite, numeroCorreto, contador;

    srand(time(NULL));
    numeroCorreto = rand() % 100;
	puts(YELLOW"Bem-vindo!"RESET);
    contador = 0;

	puts("Adivinhe o numero:");
	scanf("%d", &palpite);

    while(palpite != numeroCorreto){
        if (palpite > numeroCorreto){
            puts(BLUE"Palpite alto!"RESET);
        }else{
            puts(RED"Palpite foi baixo!"RESET);
        }
        printf("Digite seu novo palpite: ");
        scanf("%d", &palpite);
        contador = contador + 1;
    }
    puts(GREEN"Voce ganhou!"RESET);
    printf("O número de palpites foi %d\n", contador);
	puts("Fim do jogo.");
}

void HunchPlan2(){
    int palpite, numeroCorreto, contador;

    srand(time(NULL));
    numeroCorreto = rand() % 100;
	puts(YELLOW"Bem-vindo!"RESET);

	puts("Adivinhe o numero:");
	scanf("%d", &palpite);
    contador = 1;
    printf("\nNúmero de palpites até agora: %d\n", contador);
    while(palpite != numeroCorreto){
        if (palpite > numeroCorreto){
            puts(BLUE"Palpite alto!"RESET);
        }else{
            puts(RED"Palpite foi baixo!"RESET);
        }
        printf("Digite seu novo palpite: ");
        scanf("%d", &palpite);
        contador = contador + 1;
        if(contador == 5 && palpite != numeroCorreto){
            puts(RED"Perdeu, você fez 5 palpites."RESET);
            return;
        }
        printf("\nNúmero de palpites até agora: %d\n", contador);
    }
    puts(GREEN"Voce ganhou!"RESET);
    printf("O número de palpites foi %d\n", contador);
	puts("Fim do jogo.");
}
