//Generated by;
//Joaquim Breno
//Calculadora de raízes


#include <stdio.h>
#include <locale.h>
#include <math.h>

int main ()
{   
    setlocale (LC_ALL, "portuguese-brazilian");
    float a, b, c;
    float delta, x1, x2;
    char ch;
    
    /**
     * Aqui abre-se uma estrutura de repetição
     * Enquanto o valor de ch for S, ou seja , true(1), a estrutura repete
     * Caso contrário o conjunto false(0) scaneia e mostra a resposta enviada
     * Pode ser "n", "N", ... qualquer charactere;
     */
    printf("Você quer calcular? (S/N)");
    while (scanf(" %c", &ch) == 1 && printf("Resposta é %c\n", ch) > 0 && ch == 'S'){


    /**Sinaliza os coeficientes*/
    printf("Digite o coeficiente a:");
    scanf("%f", &a);
    printf("Digite o coeficiente b:"); 
    scanf("%f", &b);
    printf("Digite o coeficiente c:");
    scanf("%f", &c);

    /**Descobre se a = 0 */
    if (a == 0) {
        printf("Isso não é uma equação do segundo grau!");
        return(0);
    }
    /**Calcula o delta */
    else{
        delta =  b*b-4*(a*c);
        if( delta < 0 ) {/**Apresenta que delta negativo não tem raízes*/
           printf("Essa equação não tem resultados reais, o delta é %.2f", delta);
           return(0); 
        }
        else if( delta == 0) {/**Quando delta = 0 */
            x1 = x2 = (-1*b)/(2*a);
            printf("As raízes são : %.2f, %.2f.", x1, x2);
        }
        else {/**Quando delta > 0 */
            x1 = (-b + sqrt(delta))/(2*a);
            x2 = (-b - sqrt(delta))/(2*a);
            printf("As raízes são : %.2f, %.2f.", x1, x2);
        }
    printf("\nQuer continuar calculando? (S/N)");
    }
} 
  return(0);
}    