/**Calculadora de imc
 * Generated by;
 * Joaquim Breno
 */


#include <stdio.h>
#include <math.h>
#include <locale.h>

int main(void){
    float peso, altura, imc;
    printf("Olá! Meu nome é Kodi, seu matemático digital. Siga meus passos e seu resultado será um sucesso.\n");
    printf("Digite seu peso em kg:\n");
    scanf("%f", &peso);
    printf("Digite sua altura em metros:\n");
    scanf("%f", &altura);

    imc = peso/pow(altura,2);

    if ( imc <= 18.5 ){
        printf("Você está classificado no grupo de Baixo Peso!\n");
    }
    if ( imc > 18.5 && imc <= 25 ){
        printf("Você está classificado no grupo Normal!\n");
    }    
    if ( imc > 25 && imc <= 30 ){
        printf("Você está classificado no grupo de Sobrepeso!\n");
    }    
    if ( imc > 30 && imc < 30 ){
        printf("Você está classificado no grupo de Obesidade!\n");
    }                
return(0);
}