/**Triangular Area
 * Generated by;
 * Joaquim Breno
 */
#include <stdio.h>
#include <locale.h>

int main(void){
    setlocale(LC_ALL, "portuguese-brazilian");
    float b, h, a;
    printf("Calcule a área do triângulo\n");
    printf("Digite o valor da base do triângulos em cm:\n");
    scanf("%f", &b);
    printf("Digite o valor da altura do triângulos em cm:\n");
    scanf("%f", &h);   
    a = b*h/2;
    printf("O valor da área é %.2f centímetros quadrado\n", a);   
    return(0);
}