/**
 * A ideia desse código é 
 * definir qual número das entradas
 * tem o menor valor
 * Generated by:
 * Joaquim Breno 
 */
#include <stdio.h>
#include <locale.h>


int main(void)
{   
    float x1, x2;
    setlocale(LC_ALL, "portuguese-brazilian");
    printf("Olá, meu nome é Kodi o seu matemático digital! Siga meus passos e seu resultado será um sucesso.\n");
    
    printf("Digite o primeiro valor:\n");
    scanf("%f", &x1);
    printf("Digite o primeiro valor:\n");
    scanf("%f", &x2);

    if (x1 > x2){
        printf(" O primeiro %.2f número é maior que o segundo número %.2f!", x1, x2);
    }
    else if (x1 < x2){
        printf(" O primeiro %.2f número é menor que o segundo número %.2f!", x1, x2);
    }
    else
    {
        printf("Poxa! Os números são iguais, seja mais criativo\n");
    }
    return(0);
}